services:
  accounts:
    image: "surins/accounts:v1"
    container_name: accounts
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - systemsai
  loans:
    image: "surins/loans:v1"
    container_name: loans
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - systemsai
  cards:
    image: "surins/cards:v1"
    container_name: cards
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - systemsai
networks:
  systemsai:
    name: systemsai
    driver: "bridge"
